# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gastos',
            unique_together=set([('user_id', 'fecha')]),
        ),
    ]
