# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_auto_20180710_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
